Repository Sccr0123/Formula-1-Frenzy, pull requests merged in 2022-03, with the labels that each got.

#5 Added line 2 to ReadMe
  README.md
Labels: enhancement

#23 Created Badges for Technologies
  README.md
Labels: documentation

#30 Feature/calendar
  calendar.html
  index.html
Labels: mvp

#44 Feature/calendar
  assets/css/calendar.css
  assets/css/style.css
  calendar.html
  index.html
Labels: enhancement

#47 Restyled the calendar layout
  calendar.html
Labels: enhancement

#49 Created a new section on the readme file
  README.md
  assets/images/webpage.png
Labels: documentation

#51 Linked API Info To index.html
  assets/javascript/script.js
  index.html
Labels: enhancement

#52 Link Top Four To index.html
  index.html
Labels: enhancement

#55 Redesigned the layout for the calendar
  calendar.html
Labels: enhancement

#60 Add js for Drivers
  assets/javascript/drivers.js
  drivers.html
Labels: enhancement

#68 Feature/read me
  README.md
  assets/images/webpage.png
Labels: documentation

#69 Feature/calendar
  assets/javascript/drivers.js
  calendar.html
  drivers.html
  index.html
Labels: enhancement
